apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product
    spec:
      containers:
      - image: ydebeer/productservice
        name: productservice
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: product
  name: product
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: product
  type: ClusterIP
status:
  loadBalancer: {}
